package com.jason.saliencycamera;

import android.content.Context;
import android.graphics.BitmapFactory;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AbsListView;
import android.widget.BaseAdapter;
import android.widget.GridView;
import android.widget.ImageView;

import java.io.IOException;

/**
 * Created by Jason on 13/11/2014.
 */
public class ImageAdapter extends BaseAdapter {
    // references to our images
    public static String[] NO_FLASH_IMAGE_NAMES = {
            // The chosen one
            "both_movement3.jpg",
            "both_movement3.jpg",
            "both_movement3.jpg",
            "both_movement3.jpg",
            "camera_movement1.jpg",
            "camera_movement1.jpg",
            "camera_movement1.jpg",
            "camera_movement2.jpg",
            "camera_movement2.jpg",
            "camera_movement3.jpg",
            "camera_movement3.jpg",
            "camera_movement3.jpg",
            "camera_movement3.jpg",
            "object_movement6.jpg",
            "object_movement7.jpg",
            "object_movement7.jpg",
            "object_movement7.jpg",
            "object_movement7.jpg",
            "object_movement8.jpg",
            "object_movement8.jpg",
            "object_movement8.jpg",
            "object_movement8.jpg",
            "object_movement9.jpg",
            "object_movement9.jpg",
            "object_movement9.jpg",
            "object_movement9.jpg",
            "object_movement10.jpg",
            "object_movement10.jpg",
            "object_movement10.jpg",
            "camera_movement6.jpg",
            "camera_movement7.jpg",
            "camera_movement8.jpg",
            "camera_movement8.jpg",
            "camera_movement9.jpg",
            "camera_movement9.jpg",
            "camera_movement10.jpg",
            "camera_movement10.jpg",
            "camera_movement11.jpg",
            "camera_movement11.jpg",
            "camera_movement12.jpg",
            "camera_movement12.jpg",
            "both_movement4.jpg",
            "both_movement4.jpg",
            "both_movement5.jpg",
            "both_movement5.jpg",
            "both_movement6.jpg",
            "both_movement6.jpg",
            "both_movement7.jpg",
            "background_movement4.jpg",
            "background_movement5.jpg",
            "chess1.jpg",
            "chess2.jpg",
            "cube4.jpg",
            "elephant10.jpg",
            "elephant11.jpg",
            "elephant9.jpg",
            "elephant9.jpg",
            "plane12.jpg",
            "plane22.jpg",
            "plane25.jpg",
            "plane25.jpg",
            "plane26.jpg",
            "plane26.jpg",
            "plane27.jpg",
            "plane27.jpg",
            "plane27.jpg",
            "plane28.jpg",
            "plane30.jpg",
            "plane3.jpg",
            "plane7.jpg",
            "triangle4.jpg",
            "triangle5.jpg",
            "triangle6.jpg",
            "bear11.jpg",
            "bear12.jpg",
            "bear13.jpg",
            "bear15.jpg",
            "bear1.jpg",
            "bear2.jpg",
            "bear2.jpg",
            "bear3.jpg",
            "bear4.jpg",
            "dog5.jpg",
            "rabbit1.jpg",
            "rabbit2.jpg",
            "rabbit2.jpg",
            "rabbit3.jpg",
            "rabbit4.jpg",
            "rabbit4.jpg",
            "sina4.jpg",
            "sina4.jpg",
            "sina5.jpg",
            "sina6.jpg",
            "sina7.jpg",
            "sina7.jpg",
            "sina8.jpg",
            "sina8.jpg",
            "sina9.jpg"


//            "rabbit5.jpg",
//            // 3rd set of test case
//            "bear10.jpg",
//            "bear11.jpg",
//            "bear12.jpg",
//            "bear12.jpg",
//            "bear13.jpg",
//            "bear13.jpg",
//            "bear14.jpg",
//            "bear15.jpg",
//            "bear1.jpg",
//            "bear2.jpg",
//            "bear2.jpg",
//            "bear3.jpg",
//            "bear3.jpg",
//            "bear4.jpg",
//            "bear4.jpg",
//            "bear5.jpg",
//            "bear5.jpg",
//            "bear6.jpg",
//            "bear6.jpg",
//            "bear7.jpg",
//            "bear7.jpg",
//            "bear8.jpg",
//            "bear8.jpg",
//            "bear9.jpg",
//            "cow1.jpg",
//            "dog1.jpg",
//            "dog1.jpg",
//            "dog2.jpg",
//            "dog2.jpg",
//            "dog3.jpg",
//            "dog4.jpg",
//            "dog5.jpg",
//            "dog6.jpg",
//            "rabbit1.jpg",
//            "rabbit2.jpg",
//            "rabbit2.jpg",
//            "rabbit3.jpg",
//            "rabbit3.jpg",
//            "rabbit4.jpg",
//            "rabbit4.jpg",
//            "sina10.jpg",
//            "sina11.jpg",
//            "sina12.jpg",
//            "sina1.jpg",
//            "sina1.jpg",
//            "sina2.jpg",
//            "sina2.jpg",
//            "sina3.jpg",
//            "sina3.jpg",
//            "sina4.jpg",
//            "sina4.jpg",
//            "sina5.jpg",
//            "sina6.jpg",
//            "sina7.jpg",
//            "sina7.jpg",
//            "sina8.jpg",
//            "sina8.jpg",
//            "sina9.jpg",
//            // 2nd set of test case
//            "chess1.jpg",
//            "chess1.jpg",
//            "chess2.jpg",
//            "chess2.jpg",
//            "cube1.jpg",
//            "cube1.jpg",
//            "cube2.jpg",
//            "cube2.jpg",
//            "cube3.jpg",
//            "cube3.jpg",
//            "cube4.jpg",
//            "cube4.jpg",
//            "elephant10.jpg",
//            "elephant10.jpg",
//            "elephant11.jpg",
//            "elephant11.jpg",
//            "elephant12.jpg",
//            "elephant12.jpg",
//            "elephant13.jpg",
//            "elephant13.jpg",
//            "elephant14.jpg",
//            "elephant14.jpg",
//            "elephant15.jpg",
//            "elephant15.jpg",
//            "elephant16.jpg",
//            "elephant16.jpg",
//            "elephant17.jpg",
//            "elephant17.jpg",
//            "elephant1.jpg",
//            "elephant1.jpg",
//            "elephant2.jpg",
//            "elephant2.jpg",
//            "elephant3.jpg",
//            "elephant3.jpg",
//            "elephant4.jpg",
//            "elephant4.jpg",
//            "elephant5.jpg",
//            "elephant5.jpg",
//            "elephant6.jpg",
//            "elephant6.jpg",
//            "elephant7.jpg",
//            "elephant8.jpg",
//            "elephant9.jpg",
//            "elephant9.jpg",
//            "pillar1.jpg",
//            "pillar2.jpg",
//            "pillar2.jpg",
//            "pillar3.jpg",
//            "pillar3.jpg",
//            "plane10.jpg",
//            "plane11.jpg",
//            "plane11.jpg",
//            "plane12.jpg",
//            "plane12.jpg",
//            "plane13.jpg",
//            "plane14.jpg",
//            "plane14.jpg",
//            "plane15.jpg",
//            "plane15.jpg",
//            "plane16.jpg",
//            "plane16.jpg",
//            "plane17.jpg",
//            "plane17.jpg",
//            "plane18.jpg",
//            "plane18.jpg",
//            "plane19.jpg",
//            "plane19.jpg",
//            "plane1.jpg",
//            "plane20.jpg",
//            "plane21.jpg",
//            "plane21.jpg",
//            "plane22.jpg",
//            "plane22.jpg",
//            "plane23.jpg",
//            "plane23.jpg",
//            "plane24.jpg",
//            "plane24.jpg",
//            "plane25.jpg",
//            "plane25.jpg",
//            "plane25.jpg",
//            "plane26.jpg",
//            "plane26.jpg",
//            "plane26.jpg",
//            "plane27.jpg",
//            "plane27.jpg",
//            "plane27.jpg",
//            "plane28.jpg",
//            "plane28.jpg",
//            "plane28.jpg",
//            "plane29.jpg",
//            "plane29.jpg",
//            "plane29.jpg",
//            "plane2.jpg",
//            "plane2.jpg",
//            "plane30.jpg",
//            "plane30.jpg",
//            "plane30.jpg",
//            "plane31.jpg",
//            "plane31.jpg",
//            "plane32.jpg",
//            "plane32.jpg",
//            "plane33.jpg",
//            "plane33.jpg",
//            "plane34.jpg",
//            "plane34.jpg",
//            "plane35.jpg",
//            "plane35.jpg",
//            "plane36.jpg",
//            "plane36.jpg",
//            "plane37.jpg",
//            "plane37.jpg",
//            "plane38.jpg",
//            "plane38.jpg",
//            "plane39.jpg",
//            "plane39.jpg",
//            "plane3.jpg",
//            "plane3.jpg",
//            "plane40.jpg",
//            "plane40.jpg",
//            "plane41.jpg",
//            "plane41.jpg",
//            "plane42.jpg",
//            "plane42.jpg",
//            "plane43.jpg",
//            "plane4.jpg",
//            "plane4.jpg",
//            "plane5.jpg",
//            "plane6.jpg",
//            "plane6.jpg",
//            "plane7.jpg",
//            "plane7.jpg",
//            "plane8.jpg",
//            "plane8.jpg",
//            "plane9.jpg",
//            "plane9.jpg",
//            "redcube1.jpg",
//            "redcube1.jpg",
//            "redcube2.jpg",
//            "redcube2.jpg",
//            "redcube3.jpg",
//            "triangle1.jpg",
//            "triangle1.jpg",
//            "triangle2.jpg",
//            "triangle2.jpg",
//            "triangle3.jpg",
//            "triangle4.jpg",
//            "triangle5.jpg",
//            "triangle5.jpg",
//            "triangle6.jpg",
//            "triangle6.jpg",
//            // 1st set of test case
//            "background_movement1.jpg",
//            "background_movement1.jpg",
//            "background_movement2.jpg",
//            "background_movement2.jpg",
//            "background_movement3.jpg",
//            "background_movement3.jpg",
//            "both_movement1.jpg",
//            "both_movement1.jpg",
//            "both_movement1.jpg",
//            "both_movement1.jpg",
//            "both_movement1.jpg",
//            "both_movement1.jpg",
//            "both_movement2.jpg",
//            "both_movement2.jpg",
//            "both_movement2.jpg",
//            "both_movement2.jpg",
//            "both_movement2.jpg",
//            "both_movement3.jpg",
//            "both_movement3.jpg",
//            "both_movement3.jpg",
//            "both_movement3.jpg",
//            "both_movement3.jpg",
//            "both_movement3.jpg",
//            "both_movement3.jpg",
//            "camera_movement1.jpg",
//            "camera_movement1.jpg",
//            "camera_movement1.jpg",
//            "camera_movement1.jpg",
//            "camera_movement1.jpg",
//            "camera_movement1.jpg",
//            "camera_movement1.jpg",
//            "camera_movement1.jpg",
//            "camera_movement2.jpg",
//            "camera_movement2.jpg",
//            "camera_movement2.jpg",
//            "camera_movement2.jpg",
//            "camera_movement2.jpg",
//            "camera_movement2.jpg",
//            "camera_movement3.jpg",
//            "camera_movement3.jpg",
//            "camera_movement3.jpg",
//            "camera_movement3.jpg",
//            "camera_movement3.jpg",
//            "object_change1.jpg",
//            "object_change1.jpg",
//            "object_change1.jpg",
//            "object_change1.jpg",
//            "object_change2.jpg",
//            "object_change2.jpg",
//            "object_change2.jpg",
//            "object_change2.jpg",
//            "object_change2.jpg",
//            "object_change2.jpg",
//            "object_movement1.jpg",
//            "object_movement1.jpg",
//            "object_movement1.jpg",
//            "object_movement1.jpg",
//            "object_movement1.jpg",
//            "object_movement1.jpg",
//            "object_movement1.jpg",
//            "object_movement1.jpg",
//            "object_movement2.jpg",
//            "object_movement2.jpg",
//            "object_movement2.jpg",
//            "object_movement2.jpg",
//            "object_movement2.jpg",
//            "object_movement2.jpg",
//            "object_movement3.jpg",
//            "object_movement3.jpg",
//            "object_movement3.jpg",
//            "object_movement3.jpg",
//            "object_movement3.jpg",
//            "object_movement3.jpg",
//            "object_movement3.jpg",
//            "object_movement4.jpg",
//            "object_movement4.jpg",
//            "object_movement4.jpg",
//            "object_movement5.jpg",
//            "object_movement5.jpg",
//            "object_movement5.jpg",
//            "object_movement6.jpg",
//            "object_movement6.jpg",
//            "object_movement6.jpg",
//            "object_movement7.jpg",
//            "object_movement7.jpg",
//            "object_movement7.jpg",
//            "object_movement7.jpg",
//            "object_movement8.jpg",
//            "object_movement8.jpg",
//            "object_movement8.jpg",
//            "object_movement8.jpg",
//            "object_movement9.jpg",
//            "object_movement9.jpg",
//            "object_movement9.jpg",
//            "object_movement9.jpg",
//            "object_movement10.jpg",
//            "object_movement10.jpg",
//            "object_movement10.jpg",
//            "object_movement10.jpg",
//            "camera_movement4.jpg",
//            "camera_movement4.jpg",
//            "camera_movement5.jpg",
//            "camera_movement5.jpg",
//            "camera_movement6.jpg",
//            "camera_movement6.jpg",
//            "camera_movement7.jpg",
//            "camera_movement7.jpg",
//            "camera_movement8.jpg",
//            "camera_movement8.jpg",
//            "camera_movement9.jpg",
//            "camera_movement9.jpg",
//            "camera_movement10.jpg",
//            "camera_movement10.jpg",
//            "camera_movement11.jpg",
//            "camera_movement11.jpg",
//            "camera_movement11.jpg",
//            "camera_movement12.jpg",
//            "camera_movement12.jpg",
//            "camera_movement12.jpg",
//            "camera_movement13.jpg",
//            "camera_movement13.jpg",
//            "camera_movement13.jpg",
//            "both_movement4.jpg",
//            "both_movement4.jpg",
//            "both_movement5.jpg",
//            "both_movement5.jpg",
//            "both_movement6.jpg",
//            "both_movement6.jpg",
//            "both_movement7.jpg",
//            "background_movement4.jpg",
//            "background_movement5.jpg",
//            "background_movement6.jpg",
//            //old images
//            "tennis.jpg",
//            "tennis2.jpg",
//            "building.jpg",
//            "micky.jpg",
//            "bag.jpg",
//            "phone2.jpg",
//            "phone3.jpg",
//            "chicken.jpg",
//            "toy.jpg",
//            "3dprinting.jpg",
//            "lena2_.png"
    };
    public static final String[] FLASH_IMAGE_NAMES = {
            // The chosen one
            "both_movement3_light2.jpg",
            "both_movement3_light3.jpg",
            "both_movement3_light4.jpg",
            "both_movement3_light5.jpg",
            "camera_movement1_light3.jpg",
            "camera_movement1_light7.jpg",
            "camera_movement1_light8.jpg",
            "camera_movement2_light2.jpg",
            "camera_movement2_light3.jpg",
            "camera_movement3_light2.jpg",
            "camera_movement3_light3.jpg",
            "camera_movement3_light4.jpg",
            "camera_movement3_light5.jpg",
            "object_movement6_light1.jpg",
            "object_movement7_light1.jpg",
            "object_movement7_light2.jpg",
            "object_movement7_light3.jpg",
            "object_movement7_light4.jpg",
            "object_movement8_light1.jpg",
            "object_movement8_light2.jpg",
            "object_movement8_light3.jpg",
            "object_movement8_light4.jpg",
            "object_movement9_light1.jpg",
            "object_movement9_light2.jpg",
            "object_movement9_light3.jpg",
            "object_movement9_light4.jpg",
            "object_movement10_light1.jpg",
            "object_movement10_light2.jpg",
            "object_movement10_light4.jpg",
            "camera_movement6_light2.jpg",
            "camera_movement7_light2.jpg",
            "camera_movement8_light1.jpg",
            "camera_movement8_light2.jpg",
            "camera_movement9_light1.jpg",
            "camera_movement9_light2.jpg",
            "camera_movement10_light1.jpg",
            "camera_movement10_light2.jpg",
            "camera_movement11_light2.jpg",
            "camera_movement11_light3.jpg",
            "camera_movement12_light2.jpg",
            "camera_movement12_light3.jpg",
            "both_movement4_light1.jpg",
            "both_movement4_light2.jpg",
            "both_movement5_light1.jpg",
            "both_movement5_light2.jpg",
            "both_movement6_light1.jpg",
            "both_movement6_light2.jpg",
            "both_movement7_light1.jpg",
            "background_movement4_light1.jpg",
            "background_movement5_light1.jpg",
            "chess1_light1.jpg",
            "chess2_light2.jpg",
            "cube4_light2.jpg",
            "elephant10_light3.jpg",
            "elephant11_light3.jpg",
            "elephant9_light2.jpg",
            "elephant9_light3.jpg",
            "plane12_light2.jpg",
            "plane22_light2.jpg",
            "plane25_light2.jpg",
            "plane25_light3.jpg",
            "plane26_light2.jpg",
            "plane26_light3.jpg",
            "plane27_light1.jpg",
            "plane27_light2.jpg",
            "plane27_light3.jpg",
            "plane28_light3.jpg",
            "plane30_light3.jpg",
            "plane3_light2.jpg",
            "plane7_light2.jpg",
            "triangle4_light1.jpg",
            "triangle5_light2.jpg",
            "triangle6_light2.jpg",
            "bear11_light1.jpg",
            "bear12_light2.jpg",
            "bear13_light2.jpg",
            "bear15_light1.jpg",
            "bear1_light1.jpg",
            "bear2_light1.jpg",
            "bear2_light2.jpg",
            "bear3_light1.jpg",
            "bear4_light2.jpg",
            "dog5_light1.jpg",
            "rabbit1_light1.jpg",
            "rabbit2_light1.jpg",
            "rabbit2_light2.jpg",
            "rabbit3_light2.jpg",
            "rabbit4_light1.jpg",
            "rabbit4_light2.jpg",
            "sina4_light1.jpg",
            "sina4_light2.jpg",
            "sina5_light1.jpg",
            "sina6_light1.jpg",
            "sina7_light1.jpg",
            "sina7_light2.jpg",
            "sina8_light1.jpg",
            "sina8_light2.jpg",
            "sina9_light1.jpg"

//
//            "rabbit5_light1.jpg",
//            // 3rd set of test case
//            "bear10_light1.jpg",
//            "bear11_light1.jpg",
//            "bear12_light1.jpg",
//            "bear12_light2.jpg",
//            "bear13_light1.jpg",
//            "bear13_light2.jpg",
//            "bear14_light1.jpg",
//            "bear15_light1.jpg",
//            "bear1_light1.jpg",
//            "bear2_light1.jpg",
//            "bear2_light2.jpg",
//            "bear3_light1.jpg",
//            "bear3_light2.jpg",
//            "bear4_light1.jpg",
//            "bear4_light2.jpg",
//            "bear5_light1.jpg",
//            "bear5_light2.jpg",
//            "bear6_light1.jpg",
//            "bear6_light2.jpg",
//            "bear7_light1.jpg",
//            "bear7_light2.jpg",
//            "bear8_light1.jpg",
//            "bear8_light2.jpg",
//            "bear9_light1.jpg",
//            "cow1_light1.jpg",
//            "dog1_light1.jpg",
//            "dog1_light2.jpg",
//            "dog2_light1.jpg",
//            "dog2_light2.jpg",
//            "dog3_light1.jpg",
//            "dog4_light1.jpg",
//            "dog5_light1.jpg",
//            "dog6_light1.jpg",
//            "rabbit1_light1.jpg",
//            "rabbit2_light1.jpg",
//            "rabbit2_light2.jpg",
//            "rabbit3_light1.jpg",
//            "rabbit3_light2.jpg",
//            "rabbit4_light1.jpg",
//            "rabbit4_light2.jpg",
//            "sina10_light1.jpg",
//            "sina11_light1.jpg",
//            "sina12_light1.jpg",
//            "sina1_light1.jpg",
//            "sina1_light2.jpg",
//            "sina2_light1.jpg",
//            "sina2_light2.jpg",
//            "sina3_light1.jpg",
//            "sina3_light2.jpg",
//            "sina4_light1.jpg",
//            "sina4_light2.jpg",
//            "sina5_light1.jpg",
//            "sina6_light1.jpg",
//            "sina7_light1.jpg",
//            "sina7_light2.jpg",
//            "sina8_light1.jpg",
//            "sina8_light2.jpg",
//            "sina9_light1.jpg",
//            // 2nd set of test case
//            "chess1_light1.jpg",
//            "chess1_light2.jpg",
//            "chess2_light1.jpg",
//            "chess2_light2.jpg",
//            "cube1_light1.jpg",
//            "cube1_light2.jpg",
//            "cube2_light1.jpg",
//            "cube2_light2.jpg",
//            "cube3_light1.jpg",
//            "cube3_light2.jpg",
//            "cube4_light1.jpg",
//            "cube4_light2.jpg",
//            "elephant10_light1.jpg",
//            "elephant10_light3.jpg",
//            "elephant11_light1.jpg",
//            "elephant11_light3.jpg",
//            "elephant12_light1.jpg",
//            "elephant12_light2.jpg",
//            "elephant13_light1.jpg",
//            "elephant13_light2.jpg",
//            "elephant14_light1.jpg",
//            "elephant14_light2.jpg",
//            "elephant15_light1.jpg",
//            "elephant15_light2.jpg",
//            "elephant16_light1.jpg",
//            "elephant16_light2.jpg",
//            "elephant17_light1.jpg",
//            "elephant17_light2.jpg",
//            "elephant1_light1.jpg",
//            "elephant1_light2.jpg",
//            "elephant2_light1.jpg",
//            "elephant2_light2.jpg",
//            "elephant3_light1.jpg",
//            "elephant3_light2.jpg",
//            "elephant4_light1.jpg",
//            "elephant4_light2.jpg",
//            "elephant5_light1.jpg",
//            "elephant5_light2.jpg",
//            "elephant6_light1.jpg",
//            "elephant6_light2.jpg",
//            "elephant7_light1.jpg",
//            "elephant8_light1.jpg",
//            "elephant9_light2.jpg",
//            "elephant9_light3.jpg",
//            "pillar1_light1.jpg",
//            "pillar2_light1.jpg",
//            "pillar2_light2.jpg",
//            "pillar3_light1.jpg",
//            "pillar3_light2.jpg",
//            "plane10_light1.jpg",
//            "plane11_light1.jpg",
//            "plane11_light2.jpg",
//            "plane12_light1.jpg",
//            "plane12_light2.jpg",
//            "plane13_light1.jpg",
//            "plane14_light1.jpg",
//            "plane14_light2.jpg",
//            "plane15_light1.jpg",
//            "plane15_light2.jpg",
//            "plane16_light1.jpg",
//            "plane16_light2.jpg",
//            "plane17_light1.jpg",
//            "plane17_light2.jpg",
//            "plane18_light1.jpg",
//            "plane18_light2.jpg",
//            "plane19_light1.jpg",
//            "plane19_light2.jpg",
//            "plane1_light1.jpg",
//            "plane20_light1.jpg",
//            "plane21_light1.jpg",
//            "plane21_light2.jpg",
//            "plane22_light1.jpg",
//            "plane22_light2.jpg",
//            "plane23_light1.jpg",
//            "plane23_light2.jpg",
//            "plane24_light1.jpg",
//            "plane24_light2.jpg",
//            "plane25_light1.jpg",
//            "plane25_light2.jpg",
//            "plane25_light3.jpg",
//            "plane26_light1.jpg",
//            "plane26_light2.jpg",
//            "plane26_light3.jpg",
//            "plane27_light1.jpg",
//            "plane27_light2.jpg",
//            "plane27_light3.jpg",
//            "plane28_light1.jpg",
//            "plane28_light2.jpg",
//            "plane28_light3.jpg",
//            "plane29_light1.jpg",
//            "plane29_light2.jpg",
//            "plane29_light3.jpg",
//            "plane2_light1.jpg",
//            "plane2_light2.jpg",
//            "plane30_light1.jpg",
//            "plane30_light2.jpg",
//            "plane30_light3.jpg",
//            "plane31_light1.jpg",
//            "plane31_light2.jpg",
//            "plane32_light1.jpg",
//            "plane32_light2.jpg",
//            "plane33_light1.jpg",
//            "plane33_light2.jpg",
//            "plane34_light1.jpg",
//            "plane34_light2.jpg",
//            "plane35_light1.jpg",
//            "plane35_light2.jpg",
//            "plane36_light1.jpg",
//            "plane36_light2.jpg",
//            "plane37_light1.jpg",
//            "plane37_light2.jpg",
//            "plane38_light1.jpg",
//            "plane38_light2.jpg",
//            "plane39_light1.jpg",
//            "plane39_light2.jpg",
//            "plane3_light1.jpg",
//            "plane3_light2.jpg",
//            "plane40_light1.jpg",
//            "plane40_light2.jpg",
//            "plane41_light1.jpg",
//            "plane41_light2.jpg",
//            "plane42_light1.jpg",
//            "plane42_light2.jpg",
//            "plane43_light1.jpg",
//            "plane4_light1.jpg",
//            "plane4_light2.jpg",
//            "plane5_light1.jpg",
//            "plane6_light1.jpg",
//            "plane6_light2.jpg",
//            "plane7_light1.jpg",
//            "plane7_light2.jpg",
//            "plane8_light1.jpg",
//            "plane8_light2.jpg",
//            "plane9_light1.jpg",
//            "plane9_light2.jpg",
//            "redcube1_light1.jpg",
//            "redcube1_light2.jpg",
//            "redcube2_light1.jpg",
//            "redcube2_light2.jpg",
//            "redcube3_light1.jpg",
//            "triangle1_light1.jpg",
//            "triangle1_light2.jpg",
//            "triangle2_light1.jpg",
//            "triangle2_light2.jpg",
//            "triangle3_light1.jpg",
//            "triangle4_light1.jpg",
//            "triangle5_light1.jpg",
//            "triangle5_light2.jpg",
//            "triangle6_light1.jpg",
//            "triangle6_light2.jpg",
//            // 1st set of test case
//            "background_movement1_light1.jpg",
//            "background_movement1_light2.jpg",
//            "background_movement2_light1.jpg",
//            "background_movement2_light2.jpg",
//            "background_movement3_light1.jpg",
//            "background_movement3_light2.jpg",
//            "both_movement1_light1.jpg",
//            "both_movement1_light2.jpg",
//            "both_movement1_light3.jpg",
//            "both_movement1_light4.jpg",
//            "both_movement1_light5.jpg",
//            "both_movement1_light6.jpg",
//            "both_movement2_light1.jpg",
//            "both_movement2_light2.jpg",
//            "both_movement2_light3.jpg",
//            "both_movement2_light4.jpg",
//            "both_movement2_light5.jpg",
//            "both_movement3_light1.jpg",
//            "both_movement3_light2.jpg",
//            "both_movement3_light3.jpg",
//            "both_movement3_light4.jpg",
//            "both_movement3_light5.jpg",
//            "both_movement3_light6.jpg",
//            "both_movement3_light7.jpg",
//            "camera_movement1_light1.jpg",
//            "camera_movement1_light2.jpg",
//            "camera_movement1_light3.jpg",
//            "camera_movement1_light4.jpg",
//            "camera_movement1_light5.jpg",
//            "camera_movement1_light6.jpg",
//            "camera_movement1_light7.jpg",
//            "camera_movement1_light8.jpg",
//            "camera_movement2_light1.jpg",
//            "camera_movement2_light2.jpg",
//            "camera_movement2_light3.jpg",
//            "camera_movement2_light4.jpg",
//            "camera_movement2_light5.jpg",
//            "camera_movement2_light6.jpg",
//            "camera_movement3_light1.jpg",
//            "camera_movement3_light2.jpg",
//            "camera_movement3_light3.jpg",
//            "camera_movement3_light4.jpg",
//            "camera_movement3_light5.jpg",
//            "object_change1_light1.jpg",
//            "object_change1_light2.jpg",
//            "object_change1_light3.jpg",
//            "object_change1_light4.jpg",
//            "object_change2_light1.jpg",
//            "object_change2_light2.jpg",
//            "object_change2_light3.jpg",
//            "object_change2_light4.jpg",
//            "object_change2_light5.jpg",
//            "object_change2_light6.jpg",
//            "object_movement1_light1.jpg",
//            "object_movement1_light2.jpg",
//            "object_movement1_light3.jpg",
//            "object_movement1_light4.jpg",
//            "object_movement1_light5.jpg",
//            "object_movement1_light6.jpg",
//            "object_movement1_light7.jpg",
//            "object_movement1_light8.jpg",
//            "object_movement2_light1.jpg",
//            "object_movement2_light2.jpg",
//            "object_movement2_light3.jpg",
//            "object_movement2_light4.jpg",
//            "object_movement2_light5.jpg",
//            "object_movement2_light6.jpg",
//            "object_movement3_light1.jpg",
//            "object_movement3_light2.jpg",
//            "object_movement3_light3.jpg",
//            "object_movement3_light4.jpg",
//            "object_movement3_light5.jpg",
//            "object_movement3_light6.jpg",
//            "object_movement3_light7.jpg",
//            "object_movement4_light1.jpg",
//            "object_movement4_light2.jpg",
//            "object_movement4_light3.jpg",
//            "object_movement5_light1.jpg",
//            "object_movement5_light2.jpg",
//            "object_movement5_light3.jpg",
//            "object_movement6_light1.jpg",
//            "object_movement6_light2.jpg",
//            "object_movement6_light3.jpg",
//            "object_movement7_light1.jpg",
//            "object_movement7_light2.jpg",
//            "object_movement7_light3.jpg",
//            "object_movement7_light4.jpg",
//            "object_movement8_light1.jpg",
//            "object_movement8_light2.jpg",
//            "object_movement8_light3.jpg",
//            "object_movement8_light4.jpg",
//            "object_movement9_light1.jpg",
//            "object_movement9_light2.jpg",
//            "object_movement9_light3.jpg",
//            "object_movement9_light4.jpg",
//            "object_movement10_light1.jpg",
//            "object_movement10_light2.jpg",
//            "object_movement10_light3.jpg",
//            "object_movement10_light4.jpg",
//            "camera_movement4_light1.jpg",
//            "camera_movement4_light2.jpg",
//            "camera_movement5_light1.jpg",
//            "camera_movement5_light2.jpg",
//            "camera_movement6_light1.jpg",
//            "camera_movement6_light2.jpg",
//            "camera_movement7_light1.jpg",
//            "camera_movement7_light2.jpg",
//            "camera_movement8_light1.jpg",
//            "camera_movement8_light2.jpg",
//            "camera_movement9_light1.jpg",
//            "camera_movement9_light2.jpg",
//            "camera_movement10_light1.jpg",
//            "camera_movement10_light2.jpg",
//            "camera_movement11_light1.jpg",
//            "camera_movement11_light2.jpg",
//            "camera_movement11_light3.jpg",
//            "camera_movement12_light1.jpg",
//            "camera_movement12_light2.jpg",
//            "camera_movement12_light3.jpg",
//            "camera_movement13_light1.jpg",
//            "camera_movement13_light2.jpg",
//            "camera_movement13_light3.jpg",
//            "both_movement4_light1.jpg",
//            "both_movement4_light2.jpg",
//            "both_movement5_light1.jpg",
//            "both_movement5_light2.jpg",
//            "both_movement6_light1.jpg",
//            "both_movement6_light2.jpg",
//            "both_movement7_light1.jpg",
//            "background_movement4_light1.jpg",
//            "background_movement5_light1.jpg",
//            "background_movement6_light1.jpg",
//            //old images
//            "tennis_lighted.jpg",
//            "tennis2_lighted.jpg",
//            "building_lighted.jpg",
//            "micky_lighted.jpg",
//            "bag_lighted.jpg",
//            "phone2_lighted.jpg",
//            "phone3_lighted.jpg",
//            "chicken_lighted.jpg",
//            "toy_lighted.jpg",
//            "3dprinting_lighted.jpg",
//            "lena1_.png"
    };

    private Context mContext;
    private GridView mGridView;

    public ImageAdapter(Context c, GridView g) {
        mContext = c;
        mGridView = g;
    }

    public int getCount() {
        return NO_FLASH_IMAGE_NAMES.length;
    }

    public Object getItem(int position) {
        return null;
    }

    public long getItemId(int position) {
        return 0;
    }

    // create a new ImageView for each item referenced by the Adapter
    public View getView(int position, View convertView, ViewGroup parent) {
        ImageView imageView;
        if (convertView == null) {  // if it's not recycled, initialize some attributes
            imageView = new ImageView(mContext);
//            imageView.setLayoutParams(new GridView.LayoutParams(GridView.LayoutParams.MATCH_PARENT, (int) (mGridView.getHeight()/2.5)));
            imageView.setLayoutParams(new GridView.LayoutParams(GridView.LayoutParams.MATCH_PARENT, 250));
            imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
//            imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
            imageView.setPadding(8, 8, 8, 8);
        } else {
            imageView = (ImageView) convertView;
        }

//        imageView.setImageResource(NO_FLASH_IMAGE_NAMES[position]);
        try {
//            imageView.setImageBitmap(BitmapFactory.decodeStream(mContext.getAssets().open(NO_FLASH_IMAGE_NAMES[position])));
            imageView.setImageBitmap(BitmapFactory.decodeStream(mContext.getAssets().open(FLASH_IMAGE_NAMES[position])));
        } catch (IOException e) {
            e.printStackTrace();
        }
        return imageView;
    }


}
